### ISSUE TITLE
Error when building in NixOS

### ISSUE THREAD

**Issue by milogert** [rasulomaroff/reactive.nvim#10]
I am getting an error when building this in NixOS, regarding a duplicate help tag in the documentation.

```
E154: Duplicate tag "reactive.nvim-table-of-contents" in file /nix/store/.../doc/reactive.nvim.txtFailed to build help tags!
```

I believe it has to do with these two lines:

https://github.com/rasulomaroff/reactive.nvim/blob/70e71dd386f30308bb5f8ea8296c0ad8f2e1dbc8/doc/reactive.nvim.txt#L4

https://github.com/rasulomaroff/reactive.nvim/blob/70e71dd386f30308bb5f8ea8296c0ad8f2e1dbc8/doc/reactive.nvim.txt#L30

One of those should be changed to be different so there are not duplicate tags. Let me know if you need more information!

**Comment by rasulomaroff** [comment]
@milogert hi there! I changed it to be `contents` instead. Could you please check now?
