### ISSUE TITLE
Indentation issues

### ISSUE THREAD

**Issue by OXY2DEV** [rasulomaroff/reactive.nvim#11]
`raeactive.nvim` is causing issues with the indentation of `.html` file.

Without `reactive.nvim`
![Screenshot_2024-02-05-23-49-34-390_com termux-edit](https://github.com/rasulomaroff/reactive.nvim/assets/122956967/0afff723-95ad-4496-b264-0bc69b9a32ed)

With `reactive.nvim`
![Screenshot_2024-02-05-22-32-36-233_com termux-edit](https://github.com/rasulomaroff/reactive.nvim/assets/122956967/d1df1590-4698-4a1c-b661-07a4bba957ca)

[All plugins were disabled when I tested this]

Is there a particular reason why it only affects `.html` files?

Every other file type I had seems to work normally except for this one.

**Comment by rasulomaroff** [comment]
Hi there! I don't think this is `reactive.nvim` issue since the plugin itself doesn't do anything except applying highlights.

I tested on my machine and everything works fine. So, the problem can be in other plugins you have.

https://github.com/rasulomaroff/reactive.nvim/assets/80093436/b26ded36-77e7-4b29-b3a0-ae84a5bfabf9

**Comment by OXY2DEV** [comment]
I already did that. The problem only appears if I enable `reactive.nvim`. but just to be sure I disabled everything and only enabled `reactive` but the issue was still there. So, there is no plugins conflicting with reactive that's for sure.

Can you confirm that the issue on your machine?

**Comment by OXY2DEV** [comment]
> @OXY2DEV I would suggest trying disabling a half of your plugins and then check if this problem exists. If so, disable another half of remained plugins etc. If the problem is gone, try doing the same in the previously disabled half and find a culprit.

Found it. It's `statuscol.nvim`. The odd part is this bug only appears when both plugins are enabled, but doesn't if any one of them is disabled.

![Screenshot_2024-02-06-08-09-35-532_com termux-edit](https://github.com/rasulomaroff/reactive.nvim/assets/122956967/e93b0d91-d850-4208-9da5-d9f1f2bd69c8)

**Comment by luukvbaal** [comment]
I was able to reproduce this issue with just `:set statuscolumn=%l`. Not sure why but this seems to break the treesitter indentation in combination with this plugin. `:TSToggle indent` restores the correct behavior at least.

**Comment by rasulomaroff** [comment]
@luukvbaal oh, didn't notice you actually answered here and replied to you in the mentioned issue. Anyway, thank you for you time spent on this!

It becomes even more weird when you realize that I don't do anything with the `statuscolumn` option. I attached the video at the beginning showing that everything works perfect without `statuscolumn` in my case. And when that option is combined with `winhighlight` it somehow breaks TS indents...

**Comment by luukvbaal** [comment]
Yeah it is weird. TBH it seems unlikely that it has something to do with this plugin. As you are familiar with what exactly this plugin does, perhaps you are able to reduce the steps required to break indentation and open an issue at the nvim-treesitter tracker?

**Comment by luukvbaal** [comment]
Did some more investigating, commenting out this line "unbreaks" the indentation
https://github.com/rasulomaroff/reactive.nvim/blob/c7089808d30ca5c1bfd42eb57d2c3fc43e815190/lua/reactive/highlight.lua#L14

Not too familiar with treesitter but perhaps this redraw somehow incorrectly validates the tree after inserting a newline.

**Comment by rasulomaroff** [comment]
@luukvbaal there're only 2 places where I would check

1. `redraw` command
2. setting `winhighlight` option

I don't remember doing anything else that could somehow affect the neovim's behavior
I believe you have already found the culprit of all of it - `redraw` in combination with `statuscolumn` (or without?)

**Comment by luukvbaal** [comment]
Yeah, I was able to reproduce without this plugin by just doing `au ModeChanged * redraw!`. Still working on reproducing from `--clean`.

> No idea why but setting 'statuscolumn' in combination with this plugin seems to break treesitter indentation. `:TSToggle indent` restores the correct behavior at least.

This assumption was wrong btw. I incorrectly assumed treesitter indentation was enabled by default. `TSToggle indent` restores correct indentation in the repro because it is **en**abled.
I suppose the issue is with `statuscolumn`, `redraw` and the `html.vim` indent plugin then...

**Comment by OXY2DEV** [comment]
Just wanted to add this temporary solution, in case someone stumbled in this same issue.

Setting `{ indent = { enable = true } }` does fix the issue it somehow disables `nvim-cmp` completions. So you also need to install `cmp-treesitter` and add it to the source table which fixes it.

Now everything works as intended
![Screenshot_2024-02-13-12-13-21-662_com termux-edit](https://github.com/rasulomaroff/reactive.nvim/assets/122956967/a8a734cc-e79f-43af-912d-216cd2133ae5)
