### ISSUE TITLE
Can you share your config? I am not seeing any cursorline hl changes

### ISSUE THREAD

**Issue by daUnknownCoder** [rasulomaroff/reactive.nvim#17]
So good work on this plugin, its one hell of a productivity booster, but im not able to set it up.

This is my config:
```lua
  -- Mode Cursorline
  {
    "rasulomaroff/reactive.nvim",
    event = { "LazyFile" },
    config = function()
      local reactive = require("reactive")
      reactive.setup()
    end,
  },

```

note that im using this with another plugin:
```lua
  -- Cursorline
  {
    "tummetott/reticle.nvim",
    event = { "LazyFile" },
    opts = {
      disable_in_insert = false,
    },
  },
```
i hope it doesnt affect it coz im not seeing any cursorline highlight changes

**Comment by rasulomaroff** [comment]
Hi there! If you want to use default configuration, replace your code with:

```lua
require('reactive').setup {
  builtin = {
    cursorline = true,
    cursor = true,
    modemsg = true
  }
}
```

Built-in presets are turned off by default, this is why you have to enable them explicitly.

I'm also not sure what `LazyFile` event is for. In my case I use it with 'VeryLazy' event.

If you want to use `reactive` with your own preset instead, then please refer to [this part](https://github.com/rasulomaroff/reactive.nvim#advanced) of documentation. Feel free to ask any other questions :)

**Comment by daUnknownCoder** [comment]
> I'm also not sure what `LazyFile` event is for. In my case I use it with `VeryLazy` event.

lazyfile event can be called the father of `VimEnter` ig, coz it loads all plugins when i directly open it into a file like `nvim some.file` so its good for treesitter and lspconfig stuff, shamelessly stole from [LazyVim](https://github.com/LazyVim/LazyVim) distro tho 😃

**Comment by daUnknownCoder** [comment]
> Built-in presets are turned off by default, this is why you have to enable them explicitly.

oh thanks that works, ill try making my own preset tho 👍🏻
