### ISSUE TITLE
Highlighting absent when doing yank, change, and sometimes delete operations.

### ISSUE THREAD

**Issue by zspekt** [rasulomaroff/reactive.nvim#4]
Added the following lines, as recommended on the gh page.

```
require("reactive").setup {
  builtin = {
    cursorline = true,
    cursor = true,
    modemsg = true,
  },
}
```

The insert, replace, normal and visual mode highlights always work properly. The yank and change mode ones never do, and the delete mode highlight works for a bit, and then it stops for no apparent reason. I don't know much about neovim so I apologize if I completely missed something essential. Great work btw, it's a really nice plugin. 

PD: when the delete mode highlight stops working, it'll sometimes be visible **after** finishing or cancelling the action, but only for a split sec. I haven't been able to replicate this with the other modes.

**Comment by rasulomaroff** [comment]
https://github.com/rasulomaroff/reactive.nvim/discussions/2#discussioncomment-8212606

Can you refer to this?

**Comment by rasulomaroff** [comment]
@zspekt If you can refer to that answer, then I think I should include this info to the README file, because it's not really a bug and I don't want to mislead you guys.
It's just we have those plugins that utilize default operator keys :)

Anyway, thank you and waiting for your clarification!

**Comment by rasulomaroff** [comment]
Closing this as no answer has been provided and the error doesn't really seem to happen. Feel free to reopen if it still occurs.
