### ISSUE TITLE
Cursor Color

### ISSUE THREAD

**Issue by bartopine** [rasulomaroff/reactive.nvim#6]
Hello .. I am trying to change the color of my cursor  whenever I enter insertmode but i am not successful in doing so.
I have manage to change the cursorlineNr etc.
But changing the color of the Cursor itself seems not to work.
![123](https://github.com/rasulomaroff/reactive.nvim/assets/125934754/38fcd628-83f7-4789-909e-854ef2d39648)

I am really happy with the plugin so far! :)

**Comment by rasulomaroff** [comment]
Hi there! The thing is that the `Cursor` highlights aren't supported in 'winhighlight' option in Neovim (and actually it makes no sense since there aren't multiple cursors yet).
Just move it to the `hl` section

```lua
modes = {
  i = {
    hl = {
      Cursor = { bg = '#fabd2f' }
    },
    winhl = {
      -- your other highlights
    }
  }
}
```

**Comment by bartopine** [comment]
Thank you! :)

**Comment by bartopine** [comment]
Thank you for the help! .. The color still does not change eventhough i have moved it to the hl section.. I think it has something to do with the fact that I am using Windows Terminal .. but thanks a lot anyways 👍

**Comment by rasulomaroff** [comment]
@bartopine you can take a look at this file inside the repo: https://github.com/rasulomaroff/reactive.nvim/blob/main/lua/reactive/builtin/cursor.lua

Maybe you misspelled something. Is `Cursor` highligh actually applied to your `vim.opt.guicursor` option?

**Comment by bartopine** [comment]
Hello!.. 

I have tried doing the same thing but still .. i can't manage to make the Cursor change it's colors.

here is my setting ..
![123](https://github.com/rasulomaroff/reactive.nvim/assets/125934754/cb376298-f592-4b55-ae1b-1e1de66d383b)

**Comment by rasulomaroff** [comment]
@bartopine look at your 6 and 4 relative lines.
after `vim.opt.guicursor:append("a:CustomCursor")` you're setting it to the empty line with `vim.o.guicursor = ""`
Remove the latter
