### ISSUE TITLE
Question regarding `add_preset`

### ISSUE THREAD

**Issue by OXY2DEV** [rasulomaroff/reactive.nvim#9]
`add_preset` isn't adding my preset.

What am I doing wrong?

![Screenshot_2024-02-03-07-42-57-724_com termux-edit](https://github.com/rasulomaroff/reactive.nvim/assets/122956967/fad625a5-e1ca-45b9-a6d7-ccc9f1a12ea4)

**Comment by rasulomaroff** [comment]
Since you already added your preset through the `add_preset` method, you don't need to load it.

`load_preset` is only needed when you put your presets in `reactive/presets` directory

**Comment by OXY2DEV** [comment]
Well, that fixed the issue.
